# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "provision-shell"
  end

  config.vm.provision "shell", inline: <<-SHELL
echo "*Vagrant Provision Shell Demo*" > /etc/motd
SHELL

end
