# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "web", primary: true do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.network "forwarded_port", guest:80, host:8080
  end
  
  config.vm.provider "virtualbox" do |v|
    v.name = "provision-ansible"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook="ansible/playbook.yml"
    ansible.sudo = true
  end

  
end
