# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "cent", primary: true do |cent|
    cent.vm.box = "centos/7"
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos7-kafka-ansible"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook="ansible/playbook.yml"
    ansible.verbose=true
  end
  
end
