# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "cent", primary: true do |cent|
    cent.vm.box = "centos/7"
    #cent.vm.network "forwarded_port", guest:80, host:8080
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos7-prov-ans-java"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook="ansible/playbook.yml"
  end
  
end
