---
- hosts: all
  become: yes

  tasks:
  - name: install nano
    yum: name=nano state=present
  - name: install ntp
    yum: name=ntp state=present
  - name: start ntp
    service: name=ntpd state=started enabled=yes

    
