# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/centos7"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "devops-first-playbook"
    vb.memory = "1024"
    vb.cpus = 4
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook="playbook.yml"
    ansible.verbose=false
  end
  
end
